### ISSUE TITLE
Next tide data not displaying correctly

### ISSUE THREAD

**Issue by acgold** [FloodCamML/FloodCamMLShiny#13]
The "next tide: Today at ___" is not displaying correctly - it a few hours ahead.

It seems to be a timezone issue, where the tide data are in local time but the Sys.time() used to find the "next tide" is using UTC?

**Comment by acgold** [comment]
New code fixed timezone issue, but now display of next tide or last tide fails when they fall on different days. 

**Example:** If current time is 9:00 pm and next tide is 1:00 am the next day, last tide will display correctly (same day as current time), but next tide will not display at all.

**Comment by anardek** [comment]
I'm guessing this has to do with our NOAA call, which only returns the tides for a single day, right?

**Comment by acgold** [comment]
Fixed with #18
