### ISSUE TITLE
Persistant data storage with google sheets

### ISSUE THREAD

**Issue by adamkemberling** [FloodCamML/FloodCamMLShiny#8]
Couple things not running correctly with the `googledrive` package. I'm uncertain whether the problem is one of a couple of things:

1. When you run the app locally for the first time in a session it asks to confirm your google account (personal account). I think when it gets packaged to deploy this request is not addressed and the googledrive package then fails to do what it needs to.
2. I think its the former, but we may need to fiddle with file locations, everything needs to be at the same directory level of the app, or in sub-folders.

There are other resources for persistant app storage that we might need to try:
https://docs.rstudio.com/shinyapps.io/Storage.html
https://deanattali.com/blog/shiny-persistent-data-storage/

**Comment by acgold** [comment]
I updated the auth to use a service account JSON token ( #10 ) and that seems to be working well. I added the file to the .gitignore, but I'll send via Slack so you can add to the main shinyapp folder. The path is stored as an environment variable in google_keys.R (I'll send updated version of this too)
