### ISSUE TITLE
clean up all the repetition in camera feed ui

### ISSUE THREAD

**Issue by adamkemberling** [FloodCamML/FloodCamMLShiny#9]
I wrote a LOT of repeated code for each of the steps involving a different camera. This was a shortcut for time, but ideally this could all be reduced to functions for each step. Would make maintenance easier as well.

**Comment by acgold** [comment]
There's a little bit on reduced repetition in #10 where I made a function to render the UI for each site

**Comment by adamkemberling** [comment]
I spent some time this morning changing repeated code in the app into functions. Got rid of a lot of redundancies and should make it much easier to link in with the model predictions. I stopped at the section for the google sheet uploads, but I think its at a testable spot if @acgold wants to take a look.

**Comment by acgold** [comment]
Fixed by @adamkemberling with #11
